services:
  server:
    build: .
    container_name: server
    ports:
      - 8080:8080

  client:
    build: ./frontend
    container_name: client
    ports:
      - 3000:5173

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sodan
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8090:8080

volumes:
  mysql: