version: 3

tasks:
  gengo:
    cmds:
      - cd api && buf generate --template buf.gen.go.yaml
  gents:
    cmds:
      - cd api && buf generate --template buf.gen.web.yaml
  rm:
    cmds:
      - docker image rm sodan-grpc-server
      - docker image rm sodan-grpc-client
  server:
    cmds:
      - cd cmd/server && go run main.go
  client:
    cmds:
      - cd cmd/client && go run main.go
  front:
    cmds:
      - cd frontend && npm run dev
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  reset:
    cmds:
      - docker copmose down -v
  log:
    cmds:
      - docker compose logs -f