version: 3

tasks:
  gen:
    cmds:
      - cd api && protoc --go_out=../pkg/grpc/pb --go_opt=paths=source_relative --go-grpc_out=../pkg/grpc/pb --go-grpc_opt=paths=source_relative *.proto
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  reset:
    cmds:
      - docker copmose down -v
  log:
    cmds:
      - docker compose logs -f